WebProgrammingProject/Controllers/BarbersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebProgrammingProject.Models;
using WebProgrammingProject.Models.db;

namespace WebProgrammingProject.Controllers
{

    [Authorize(Roles = "A")]
    public class BarbersController : Controller
    {
        private readonly Db _context;

        public BarbersController(Db context)
        {
            _context = context;
        }

        // GET: Barbers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Barber_t.ToListAsync());
        }

        // GET: Barbers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var barber = await _context.Barber_t
                .FirstOrDefaultAsync(m => m.Id == id);
            if (barber == null)
            {
                return NotFound();
            }

            return View(barber);
        }

        // GET: Barbers/Create
        public IActionResult Create()
        {
            List<int> sh_ids = (from sh in _context.Shop_t
                    select sh.Id).ToList();

            List<int> p_ids = (from p in _context.Proficiencies_t
                                select p.Id).ToList();
            var proficiencies = new Dictionary<int, string>();
            foreach (var id in p_ids)
            {
                proficiencies.Add(id,(from p in _context.Proficiencies_t where id == p.Id select p.name).FirstOrDefault());
            }
            ViewBag.prof = proficiencies;
            ViewBag.shIds = sh_ids;
            ViewBag.pIds = p_ids;

            var model = new BarberCreateViewModel
            {
                Barber = new Barber(),
                //Proficiencies = proficiencies,
                //ShopIds = sh_ids
            };
            return View(model);
        }

        // POST: Barbers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BarberCreateViewModel model, List<int> SelectedDays)
        {
            //var selectedProficiencyId = 
            //[Bind("Id,FirstName,SurName,Email,Password,StartTime,EndTime")] Barber barber, List<int> SelectedDays, Dictionary<int,string> prof, int ShopId
            /*foreach (var p  in prof)
            {
                // You can now work with the integer values or convert them back to the enum
                barber.Proficiencies.Add(p.Key);
            }
            foreach (var day in SelectedDays)
            {
                // You can now work with the integer values or convert them back to the enum
                DayOfWeekEnum selectedDay = (DayOfWeekEnum)day;
                barber.SelectedDays.Add(selectedDay);
            }*/
            //model.Proficiencies = new Dictionary<int, string>();
            //model.ShopIds = new List<int>();
            //model.Proficiencies = new List<int>();
            Barber newBarber;
            if (ModelState.IsValid)
            {
                // Extract selected ShopId and ProficiencyId from the model
                //var selectedShopId = model.Barber.ShopId;
                //var selectedProficiencyId = model.Proficiencies;

                // Initialize and populate the Barber entity from the model
                newBarber = model.Barber;
                foreach (var day in SelectedDays)
                {
                    // You can now work with the integer values or convert them back to the enum
                    DayOfWeekEnum selectedDay = (DayOfWeekEnum)day;
                    newBarber.SelectedDays.Add(selectedDay);
                }                //newBarber.Proficiencies = selectedProficiencyId;
                                 //_context.Add(barber);
                _context.Add(newBarber);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // GET: Barbers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            List<int> sh_ids = (from sh in _context.Shop_t
                                select sh.Id).ToList();
            ViewBag.shIds = sh_ids;

            if (id == null)
            {
                return NotFound();
            }

            var barber = await _context.Barber_t.FindAsync(id);
            if (barber == null)
            {
                return NotFound();
            }
            return View(barber);
        }

        // POST: Barbers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ShopId,FirstName,SurName,Email,Password")] Barber barber)
        {
            if (id != barber.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(barber);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BarberExists(barber.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(barber);
        }

        // GET: Barbers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var barber = await _context.Barber_t
                .FirstOrDefaultAsync(m => m.Id == id);
            if (barber == null)
            {
                return NotFound();
            }

            return View(barber);
        }

        // POST: Barbers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var barber = await _context.Barber_t.FindAsync(id);
            if (barber != null)
            {
                _context.Barber_t.Remove(barber);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BarberExists(int id)
        {
            return _context.Barber_t.Any(e => e.Id == id);
        }
    }
}

WebProgrammingProject/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebProgrammingProject.Models.db;

namespace WebProgrammingProject.Controllers
{
    [Authorize(Roles = "A")]
    public class CustomersController : Controller
    {
        private readonly Db _context;

        public CustomersController(Db context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Customer_t.ToListAsync());
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer_t
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,SurName,Email,Password")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer_t.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,SurName,Email,Password")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer_t
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customer_t.FindAsync(id);
            if (customer != null)
            {
                _context.Customer_t.Remove(customer);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.Customer_t.Any(e => e.Id == id);
        }
    }
}

WebProgrammingProject/Controllers/ShopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebProgrammingProject.Models;
using WebProgrammingProject.Models.db;

namespace WebProgrammingProject.Controllers
{
    [Authorize(Roles = "A")]
    public class ShopsController : Controller
    {
 
        private readonly Db _context;

        public ShopsController(Db context)
        {
            _context = context;
        }

        // GET: Shops
        public async Task<IActionResult> Index()
        {
            return View(await _context.Shop_t.ToListAsync());
        }

        // GET: Shops/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shop_t
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // GET: Shops/Create
        public IActionResult Create()
        {
            List<int> sh_ids = (from sh in _context.Shopkeeper_t
                             select sh.Id).ToList();
            ViewBag.shIds = sh_ids;
            var model = new Shop();
            return View(model);
        }

        // POST: Shops/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Address,ShopkeeperId,StartTime,EndTime,City")] Shop shop, List<int> SelectedDays)
        {
            //burayi bayagi bi elden gecirmek lazim ya offff
            foreach (var day in SelectedDays)
            {
                // You can now work with the integer values or convert them back to the enum
                DayOfWeekEnum selectedDay = (DayOfWeekEnum)day;
                shop.SelectedDays.Add(selectedDay);
            }
                if (ModelState.IsValid)
            {
                _context.Add(shop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(shop);
        }

        // GET: Shops/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            List<int> sh_ids = (from sh in _context.Shopkeeper_t
                                select sh.Id).ToList();
            ViewBag.shIds = sh_ids;
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shop_t.FindAsync(id);
            if (shop == null)
            {
                return NotFound();
            }
            return View(shop);
        }

        // POST: Shops/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Address,ShopkeeperId,StartTime,EndTime,City")] Shop shop, List<int> SelectedDays)
        {
            if (id != shop.Id)
            {
                return NotFound();
            }
            foreach (var day in SelectedDays)
            {
                // You can now work with the integer values or convert them back to the enum
                DayOfWeekEnum selectedDay = (DayOfWeekEnum)day;
                shop.SelectedDays.Add(selectedDay);
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShopExists(shop.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shop);
        }

        // GET: Shops/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shop_t
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // POST: Shops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shop = await _context.Shop_t.FindAsync(id);
            if (shop != null)
            {
                _context.Shop_t.Remove(shop);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShopExists(int id)
        {
            return _context.Shop_t.Any(e => e.Id == id);
        }
    }
}

WebProgrammingProject/Views/Shared/(OLD)_SiteLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BarberNetwork</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebProgrammingProject.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-auto bg-dark sticky-top">
                <div class="d-flex flex-sm-column flex-row flex-nowrap bg-dark align-items-center sticky-top">
                    
                    <!-- NAVBAR CONTENT-->
                    <br />
                    <a href="/" class="d-flex align-items-center pb-sm-3 mb-md-0 me-md-auto   text-warning  text-decoration-none">
                        <span class="fs-4">B<span class="d-none d-sm-inline">arber</span></span>
                        <span class="fs-4">N<span class="d-none d-sm-inline">etwork</span></span>
                    </a>

                    <ul class="nav nav-pills flex-sm-column flex-row flex-nowrap flex-shrink-1  flex-sm-grow-0 flex-grow-1 mb-sm-auto mb-0 justify-content-center align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item">
                            <a href="#" class="nav-link px-sm-0 px-2 text-warning">
                                <i class="fs-5 bi-house "></i><span class="ms-1 d-none d-sm-inline ">Home</span>
                            </a>
                        </li>
                        <li>
                            <a href="#submenu1" data-bs-toggle="collapse" class="text-warning nav-link px-sm-0 px-2">
                                <i class="fs-5 bi-speedometer2"></i><span class="ms-1 d-none d-sm-inline">Barber Shops</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="nav-link px-sm-0 px-2 text-warning">
                                <i class="fs-5 bi-table"></i><span class="ms-1 d-none d-sm-inline">Orders</span>
                            </a>
                        </li>
                        <!-- <li class="dropdown">
                            <a href="#" class="nav-link dropdown-toggle px-sm-0 px-2" id="dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fs-5 bi-bootstrap"></i><span class="ms-1 d-none d-sm-inline">Bootstrap</span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdown">
                                <li><a class="dropdown-item" href="#">New project...</a></li>
                                <li><a class="dropdown-item" href="#">Settings</a></li>
                                <li><a class="dropdown-item" href="#">Profile</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">Sign out</a></li>
                            </ul>
                        </li> -->
                        <li>
                            <a href="#" class="nav-link px-sm-0 px-2 text-warning">
                                <i class="fs-5 bi-grid"></i><span class="ms-1 d-none d-sm-inline">Products</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="nav-link px-sm-0 px-2 text-warning">
                                <i class="fs-5 bi-people"></i><span class="ms-1 d-none d-sm-inline">Customers</span>
                            </a>
                        </li>
                    </ul>

                    <div class="dropdown py-sm-4 mt-sm-auto ms-auto ms-sm-0 flex-shrink-1">
                        
                        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle text-warning" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="https://github.com/mdo.png" alt="hugenerd" width="28" height="28" class="rounded-circle">
                            <span class="d-none d-sm-inline mx-1 text-white">Joe</span>
                        </a>

                        <ul class="dropdown-menu dropdown-menu text-small shadow" aria-labelledby="dropdownUser1">
                            <li><a class="dropdown-item text-warning" href="#">Settings</a></li>
                            <li><a class="dropdown-item text-warning" href="#">Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item text-warning" href="#">Sign out</a></li>
                        </ul>

                        <!-- NAVBAR CONTENT-->

                    </div>
                </div>
            </div>

            <div class="col-sm  bg-dark p-3 min-vh-100">
                <!-- PAGE CONTENT-->
                <div>
                    <main class="">
                        @RenderBody()
                    </main>

                    <footer class="border-top footer text-muted">
                        <div class="container">
                            &copy; 2024 - WebProgrammingProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </div>
                    </footer>

                </div>
                <!-- PAGE CONTENT-->
            </div>
        </div>
    </div>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebProgrammingProject/Views/Shared/_AdminPanelLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebProgrammingProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebProgrammingProject.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <span class="fs-4 text-warning">B<span class="d-none d-sm-inline text-light">arber</span></span>
                    <span class="fs-4 text-warning">N<span class="d-none d-sm-inline text-light">etwork</span></span>
                </a>

                <button class="navbar-toggler text-warning" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="BarberShopsPage" asp-action="Privacy">Berber Mağazaları</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="BarbersPage" asp-action="Privacy">Berberler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="SettingsPage" asp-action="Privacy">Ayarlar</a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item  ms-auto">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login">GİRİŞ YAP</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item dropdown  ms-auto">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Merhaba, @User.Identity.Name
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-action="Logout" asp-controller="Account">Log out</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <!-- Sidebar -->
    <div class="d-flex">
        <div class="sidebar p-3">
            <h4 class="text-center">Admin Panel</h4>
            <hr class="text-white">
            <nav class="nav flex-column">
                <a class="nav-link active" asp-area="" asp-controller="Admin" asp-action="Index">
                    <i class="fas fa-tachometer-alt"></i> Dashboard
                </a>
                <a class="nav-link" asp-area="" asp-controller="Customers" asp-action="">
                    <i class="fas fa-users"></i> Müşteri Kontrolleri
                </a>
                <a class="nav-link" asp-area="" asp-controller="Barbers" asp-action="">
                    <i class="fas fa-user-tie"></i> Berber Kontrolleri
                </a>
                <a class="nav-link" asp-area="" asp-controller="Rendezvous" asp-action="">
                    <i class="fas fa-calendar-check"></i> Randevu Kontrolleri
                </a>
                <a class="nav-link" asp-area="" asp-controller="Proficiencies" asp-action="">
                    <i class="fas fa-calendar-check"></i> Servis Kontrolleri
                </a>
                <a class="nav-link" asp-area="" asp-controller="Shops" asp-action="">
                    <i class="fas fa-store"></i> Salon Kontrolleri
                </a>
            </nav>
        </div>
        <div class="content">
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
   

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2024 - WebProgrammingProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebProgrammingProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebProgrammingProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebProgrammingProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebProgrammingProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebProgrammingProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>